In [2]:
import pandas as pd

In [3]:
mlbsalaries=pd.read_csv('mlbsalaries.csv')

In [4]:
type(mlbsalaries)

pandas.core.frame.DataFrame

In [5]:
mlbsalaries

       Year           Player   Salary           Position                Team
0      1988        Mike Witt  1400000            Pitcher  Los Angeles Angels
1      1988  George Hendrick   989333         Outfielder  Los Angeles Angels
2      1988      Chili Davis   950000         Outfielder  Los Angeles Angels
3      1988    Brian Downing   900000  Designated Hitter  Los Angeles Angels
4      1988        Bob Boone   883000            Catcher  Los Angeles Angels
...     ...              ...      ...                ...                 ...
19538  2011   Gustavo Molina   455000            Catcher    New York Yankees
19539  2011        Ivan Nova   432900            Pitcher    New York Yankees
19540  2011     Colin Curtis   420400         Outfielder    New York Yankees
19541  2011    Eduardo Nunez   419300          Shortstop    New York Yankees
19542  2011    Reegie Corona   414000     Second Baseman    New York Yankees

[19543 rows x 5 columns]

In [6]:
m=mlbsalaries

In [7]:
m

       Year           Player   Salary           Position                Team
0      1988        Mike Witt  1400000            Pitcher  Los Angeles Angels
1      1988  George Hendrick   989333         Outfielder  Los Angeles Angels
2      1988      Chili Davis   950000         Outfielder  Los Angeles Angels
3      1988    Brian Downing   900000  Designated Hitter  Los Angeles Angels
4      1988        Bob Boone   883000            Catcher  Los Angeles Angels
...     ...              ...      ...                ...                 ...
19538  2011   Gustavo Molina   455000            Catcher    New York Yankees
19539  2011        Ivan Nova   432900            Pitcher    New York Yankees
19540  2011     Colin Curtis   420400         Outfielder    New York Yankees
19541  2011    Eduardo Nunez   419300          Shortstop    New York Yankees
19542  2011    Reegie Corona   414000     Second Baseman    New York Yankees

[19543 rows x 5 columns]

In [8]:
m.shape

(19543, 5)

In [9]:
m.columns

Index(['Year', 'Player', 'Salary', 'Position', 'Team'], dtype='object')

In [10]:
# How to find total number of records ?

In [11]:
m.shape[0]

19543

In [12]:
# 2. How to find out total number of columns?

In [13]:
m.shape[1]

5

In [14]:
# 3. Display all columns names ?

In [15]:
m.columns

Index(['Year', 'Player', 'Salary', 'Position', 'Team'], dtype='object')

In [16]:
# 4. Show only maximum salary value ?

In [17]:
import numpy as np

In [18]:
m['Salary'].max()

33000000

In [19]:
# 5. Show only mimmum salary value ?

In [20]:
m['Salary'].min()

62500

In [21]:
# 6. Show Maximim salary complete record ?

In [22]:
m.sort_values(by='Salary',ascending=False).head(2)

       Year          Player    Salary       Position              Team
17846  2009  Alex Rodriguez  33000000  Third Baseman  New York Yankees
18675  2010  Alex Rodriguez  33000000  Third Baseman  New York Yankees

In [23]:
# method 2
m[m['Salary']==m['Salary'].max()]

       Year          Player    Salary       Position              Team
17846  2009  Alex Rodriguez  33000000  Third Baseman  New York Yankees
18675  2010  Alex Rodriguez  33000000  Third Baseman  New York Yankees

In [24]:
# 7. Show Minmum salary complete record ?

In [25]:
m.sort_values(by='Salary',ascending=True).head(1)

     Year       Player  Salary Position           Team
497  1988  Jose Cecena   62500  Pitcher  Texas Rangers

In [26]:
# method 2
m[m['Salary']==m['Salary'].min()]

     Year           Player  Salary       Position                Team
21   1988      Thad Bosley   62500     Outfielder  Los Angeles Angels
22   1988      Terry Clark   62500        Pitcher  Los Angeles Angels
23   1988  Sherman Corbett   62500        Pitcher  Los Angeles Angels
24   1988       Jim Eppard   62500     Outfielder  Los Angeles Angels
25   1988     Bryan Harvey   62500        Pitcher  Los Angeles Angels
..    ...              ...     ...            ...                 ...
654  1988      Russ Morman   62500  First Baseman   Chicago White Sox
655  1988        Donn Pall   62500        Pitcher   Chicago White Sox
656  1988      Kelly Paris   62500  First Baseman   Chicago White Sox
657  1988     Melido Perez   62500        Pitcher   Chicago White Sox
658  1988  Steve Rosenberg   62500        Pitcher   Chicago White Sox

[81 rows x 5 columns]

In [27]:
# 8. Show all record Team Wise Details ?

In [28]:
m['Team']

0        Los Angeles Angels
1        Los Angeles Angels
2        Los Angeles Angels
3        Los Angeles Angels
4        Los Angeles Angels
                ...
19538      New York Yankees
19539      New York Yankees
19540      New York Yankees
19541      New York Yankees
19542      New York Yankees
Name: Team, Length: 19543, dtype: object

In [29]:
#METHOD 2
m.sort_values(by='Team',ascending=True)

       Year            Player   Salary        Position                  Team
10573  2001     Damian Miller  1250000         Catcher  Arizona Diamondbacks
8835   1999      Lenny Harris  1125000  Second Baseman  Arizona Diamondbacks
8836   1999     Greg Colbrunn   900000   First Baseman  Arizona Diamondbacks
8837   1999       Gregg Olson   850000         Pitcher  Arizona Diamondbacks
8838   1999    Byung-Hyun Kim   762500         Pitcher  Arizona Diamondbacks
...     ...               ...      ...             ...                   ...
7339   1997   Darrin Fletcher  1350000         Catcher  Washington Nationals
7340   1997     Rheal Cormier  1050000         Pitcher  Washington Nationals
7341   1997        Dave Veres   725000         Pitcher  Washington Nationals
4242   1993  Delino DeShields  1537500  Second Baseman  Washington Nationals
13301  2004    Peter Bergeron   300000      Outfielder  Washington Nationals

[19543 rows x 5 columns]

In [30]:
# 8. Show all record Year Wise Details ?

In [31]:
m['Year']

0        1988
1        1988
2        1988
3        1988
4        1988
         ...
19538    2011
19539    2011
19540    2011
19541    2011
19542    2011
Name: Year, Length: 19543, dtype: int64

In [32]:
#METHOD 2
m.sort_values(by='Year',ascending=True)

       Year         Player    Salary        Position                  Team
0      1988      Mike Witt   1400000         Pitcher    Los Angeles Angels
453    1988       Bob Walk    450000         Pitcher    Pittsburgh Pirates
454    1988   Dave Lapoint    425000         Pitcher    Pittsburgh Pirates
455    1988      Sid Bream    360000   First Baseman    Pittsburgh Pirates
456    1988  R.J. Reynolds    290000      Outfielder    Pittsburgh Pirates
...     ...            ...       ...             ...                   ...
18984  2011     Barry Zito  18500000         Pitcher  San Francisco Giants
18985  2011   Tim Lincecum  14000000         Pitcher  San Francisco Giants
18986  2011   Aaron Rowand  13600000      Outfielder  San Francisco Giants
18962  2011     Juan Uribe   5295910  Second Baseman   Los Angeles Dodgers
19542  2011  Reegie Corona    414000  Second Baseman      New York Yankees

[19543 rows x 5 columns]

In [33]:
# Show all player names where position = Pitcher ?

In [35]:
a=m.loc[m[m.Position=='Picther'].index.tolist()]['Player'].unique().tolist()
a

[]

In [36]:
n=m.loc[m[m.Position=='Pitcher'].index.tolist()]['Player'].unique().tolist()
n

['Mike Witt',
 'Dan Petry',
 'Greg Minton',
 'Kirk McCaskill',
 'Willie Fraser',
 'Chuck Finley',
 'Jack Lazorko',
 'Stew Cliburn',
 'Terry Clark',
 'Sherman Corbett',
 'Bryan Harvey',
 'Nolan Ryan',
 'Dave Smith',
 'Bob Knepper',
 'Danny Darwin',
 'Mike Scott',
 'Bob Forsch',
 'Joaquin Andujar',
 'Larry Andersen',
 'Jim Deshaies',
 'Juan Agosto',
 'Bob Welch',
 'Rick Honeycutt',
 'Dennis Eckersley',
 'Dave Stewart',
 'Storm Davis',
 'Gene Nelson',
 'Matt Young',
 'Curt Young',
 'Steve Ontiveros',
 'Eric Plunk',
 'Greg Cadaret',
 'Todd Burns',
 'Dave Stieb',
 'Jim Clancy',
 'Tom Henke',
 'Mike Flanagan',
 'Jimmy Key',
 'John Cerutti',
 'Jeff Musselman',
 'David Wells',
 'Duane Ward',
 'Tony Castillo',
 'Bruce Sutter',
 'Rick Mahler',
 'Zane Smith',
 'Jim Acker',
 'Charlie Puleo',
 'Paul Assenmacher',
 'Tom Glavine',
 'Pete Smith',
 'Jose Alvarez',
 'German Jimenez',
 'John Smoltz',
 'Teddy Higuera',
 'Mark Clear',
 'Dan Plesac',
 'Juan Nieves',
 'Bill Wegman',
 'Chris Bosio',
 'Paul Mirabella',
 'Chuck Crim',
 'Odell Jones',
 'Mike Birkbeck',
 'Dave Stapleton',
 'Don August',
 'Danny Cox',
 'Ken Dayley',
 'Jose DeLeon',
 'Todd Worrell',
 'Greg Mathews',
 'Joe Magrane',
 'Scott Terry',
 'John Costello',
 'Larry McWilliams',
 'Dan Quisenberry',
 'Rick Sutcliffe',
 'Goose Gossage',
 'Scott Sanderson',
 'Frank DiPino',
 'Al Nipper',
 'Calvin Schiraldi',
 'Jamie Moyer',
 'Pat Perry',
 'Mike Bielecki',
 'Les Lancaster',
 'Greg Maddux',
 'Drew Hall',
 'Jeff Pico',
 'Fernando Valenzuela',
 'Orel Hershiser',
 'John Tudor',
 'Jesse Orosco',
 'Jay Howell',
 'Rick Horton',
 'Alejandro Pena',
 'Tim Leary',
 'Brian Holton',
 'Tim Belcher',
 'Ramon J. Martinez',
 'Mario Soto',
 'Mike Krukow',
 'Don Robinson',
 'Atlee Hammaker',
 'Rick Reuschel',
 'Dave Dravecky',
 'Scott Garrelts',
 'Craig Lefferts',
 'Mike Lacoss',
 'Joe Price',
 'Kelly Downs',
 'Lary Sorensen',
 'Terry Mulholland',
 'Jeff Brantley',
 'Roger Samuels',
 'Bud Black',
 'Jeff Dedmon',
 'Tom Candiotti',
 'Scott Bailes',
 'Brad Havens',
 'Doug Jones',
 'Greg Swindell',
 'Rich Yett',
 'Don Gordon',
 'Jon Perlman',
 'John Farrell',
 'Rod Nichols',
 'Steve Trout',
 'Mark Langston',
 'Mike Moore',
 'Jerry Reed',
 'Rod Scurry',
 'Scott Bankhead',
 'Mike Jackson',
 'Bill Wilkinson',
 'Bill Swift',
 'Mike Campbell',
 'Mike Schooler',
 'Terry Taylor',
 'Dwight Gooden',
 'Ron Darling',
 'Bob Ojeda',
 'Roger McDowell',
 'Sid Fernandez',
 'Rick Aguilera',
 'Terry Leach',
 'Randy Myers',
 'David Cone',
 'Bob McClure',
 'Dennis Martinez',
 'Tim Burke',
 'Neal Heaton',
 'Bryn Smith',
 'Andy McGaffigan',
 'Joe Hesketh',
 'Pascual Perez',
 'Floyd Youmans',
 'Jeff Parrett',
 'John Dopson',
 'Brian Holman',
 'Tom Niedenfuer',
 'Don Aase',
 'Dave Schmidt',
 'Mark Thurmond',
 'Doug Sisk',
 'Mike Morgan',
 'Jay Tibbs',
 'Mark Williamson',
 'Jeff Ballard',
 'Jose J. Bautista',
 'Oswaldo Peraza',
 'Ed Whitson',
 'Eric Show',
 'Mark Davis',
 'Dennis Rasmussen',
 'Andy Hawkins',
 'Lance McCullers',
 'Greg Booker',
 'Jimmy Jones',
 'Mark Grant',
 'Dave Leiper',
 'Steve Bedrosian',
 'Shane Rawley',
 'Kent Tekulve',
 'David Palmer',
 'Don Carman',
 'Kevin Gross',
 'Greg A. Harris',
 'Bruce Ruffin',
 'Mike Maddux',
 'Marvin Freeman',
 'Jim Gott',
 'Jeff D. Robinson',
 'Bob Walk',
 'Dave Lapoint',
 'Brian Fisher',
 'Doug Drabek',
 'Mike Dunne',
 'Bob Kipper',
 'John Smiley',
 'Charlie Hough',
 'Cecilio Guante',
 'Mitch Williams',
 'Guy Hoffman',
 'Jeff Russell',
 'Ed Vande Berg',
 'Jose Guzman',
 'Craig McMurtry',
 'Ed Correa',
 'Bobby Witt',
 'Paul Kilgus',
 'Brad Arnsberg',
 'Ray Hayward',
 'Jose Cecena',
 'John Franco',
 'Tom Browning',
 'Frank Williams',
 'Danny Jackson',
 'Ron Robinson',
 'Rob Murphy',
 'Jose Rijo',
 'Randy St. Claire',
 'Tim Birtsas',
 'Norm Charlton',
 'Rob Dibble',
 'Roger Clemens',
 'Bob Stanley',
 'Bruce Hurst',
 'Mike Boddicker',
 'Lee Smith',
 'Dennis Boyd',
 'Mike Smithson',
 'Dennis Lamp',
 'Jeff Sellers',
 'Wes Gardner',
 'Rob Woodward',
 'Tom Bolton',
 'Charlie Leibrandt',
 'Bret Saberhagen',
 'Floyd Bannister',
 'Mark Gubicza',
 'Steve Farr',
 'Jerry Don Gleaton',
 'Jeff Montgomery',
 'Luis Aquino',
 'Israel Sanchez',
 'Jack Morris',
 'Guillermo Hernandez',
 'Frank Tanana',
 'Doyle Alexander',
 'Walt Terrell',
 'Ted Power',
 'Mike Henneman',
 'Jeff M. Robinson',
 'Paul Gibson',
 'Don Heinkel',
 'Steve Searcy',
 'Frank Viola',
 'Bert Blyleven',
 'Jeff Reardon',
 'Juan Berenguer',
 'Keith Atherton',
 'Charlie Lea',
 'Jim Winn',
 'Les Straker',
 'Allan Anderson',
 'Mark Portugal',
 'Roy Smith',
 'Fred Toliver',
 'German Gonzalez',
 'Jerry Reuss',
 'Bill Long',
 'Bobby Thigpen',
 'John Davis',
 'Jeff Bittiger',
 'Jack McDowell',
 'Donn Pall',
 'Melido Perez',
 'Steve Rosenberg',
 'Dave Righetti',
 'Richard Dotson',
 'Rick Rhoden',
 'Ron Guidry',
 'John Candelaria',
 'Tommy John',
 'Charles Hudson',
 'Neil Allen',
 'Dale Mohorcic',
 'Steve Shields',
 'Al Leiter',
 'Jim Abbott',
 'Vance Lovelace',
 'Dan Schatzeder',
 'Dave Meads',
 'Blaise Ilsley',
 'Jim Corsi',
 'Jose Nunez',
 'Todd Stottlemyre',
 'Mark Eichhorn',
 'Joe Boever',
 'Gary Eave',
 'Derek Lilliquist',
 'Mark Knudson',
 'Bryan Clutterbuck',
 'Jay Aldrich',
 'Cris Carpenter',
 'Matt Kinzer',
 'Kevin Blankenship',
 'Joe Girardi',
 'Steve Wilson',
 'Ray Searage',
 'Tim Crews',
 'Jeff Fischer',
 'Chris Jones',
 'Trevor Wilson',
 'Tim Stoddard',
 'Joe Skalski',
 'Gene Walter',
 'Erik Hanson',
 'Randy Johnson',
 'Mark Gardner',
 'Gene Harris',
 'Sergio Valdez',
 'John Habyan',
 'Kevin Hickey',
 'Bob Milacki',
 'Pete Harnisch',
 'Gregg Olson',
 'Mike Smith',
 'Pat Clements',
 'Greg W. Harris',
 'Ken Howell',
 'Bill Landrum',
 'Randy Kramer',
 'Dwayne Henry',
 'Darrel Akerfelds',
 'Kevin J. Brown',
 'Kenny Rogers',
 'Scott Scudder',
 'Steve Ellsworth',
 'Tom Gordon',
 'Dave Beard',
 'Mike Cook',
 'Gary Wayne',
 'Eric King',
 'Barry Jones',
 'Shawn Hillegas',
 'Ken Patterson',
 'Lee Guetterman',
 'Mike Erb',
 'Mike Fetters',
 'Rich Monteleone',
 'Jeff Richardson',
 'Cliff Young',
 'Bill Gullickson',
 'Charlie Kerfield',
 'Xavier Hernandez',
 'Harold Allen',
 'Ryan Bowen',
 'William Brennan',
 'Jose Cano',
 'Roger Mason',
 'Terry Wells',
 'Dave Otto',
 'Scott Chiamparino',
 'Reggie Harris',
 'Joe Law',
 'Mike Norris',
 'Ray Young',
 'Frank Wills',
 'Steve Cummings',
 'Alex A. Sanchez',
 'Willie Blair',
 'Nate Cromwell',
 'Pat Hentgen',
 'Rob MacDonald',
 'Jimmy Rogers',
 'Rick Trlicek',
 'Charlie Liebrandt',
 'Marty Clary',
 'Mike Stanton',
 'Rick Luecken',
 'Kent Mercker',
 'Rusty Reynolds',
 'Pat Gomez',
 'Tommy Greene',
 'Andy Nezelek',
 'Ben Rivera',
 'Bill Krueger',
 'Tom Filer',
 'Jaime Navarro',
 'Tony Fossas',
 'Narciso Elvira',
 'Angel Miranda',
 'Steve Monson',
 'Al Sadler',
 'Randy Veres',
 'Gibson Alba',
 'Ken Hill',
 'Howard Hilton',
 'Mike Perez',
 'Bob Tewksbury',
 'Mike Harkey',
 'Dean Wilkins',
 'Frank Castillo',
 'Kevin Coffman',
 'Joe Kraemer',
 'John Wetteland',
 'Mike Hartley',
 'Isidrio Marquez',
 'Dan Opperman',
 'Zakary Shinall',
 'Ernie Camacho',
 'John Burkett',
 'Eric Gunderson',
 'Paul McClellan',
 'Mike Remlinger',
 'Jeff Kaiser',
 'Kevin Bearse',
 'Colin Charland',
 'Carl Kellipuleole',
 'Doug Robertson',
 'Jeff Shaw',
 'Mike Walker',
 'Kevin Wickander',
 'Dennis Powell',
 'Keith Comstock',
 'Dave Burba',
 'Clint Zavaras',
 'Jeff Innis',
 'Wally Whitehurst',
 'Blaine Beatty',
 'Terry Bross',
 'Kevin D. Brown',
 'Brent Knackert',
 'Julio Machado',
 'Mike Miller',
 'Dave Trautwein',
 'Julio Valera',
 'Rich N. Thompson',
 'Chris Bennett',
 'Mario Brito',
 'Howard Farmer',
 'Steve Frey',
 'Chris Marchok',
 'Yorkis Perez',
 'Hector Rivera',
 'Mel Rojas',
 'Bill Sampen',
 'Ben McDonald',
 'Eric Bell',
 'Dave Johnson',
 'John Mitchell',
 'Mickey Weston',
 'Curt Schilling',
 'Chris Myers',
 'Anthony Telford',
 'Andy Benes',
 'Eric Nolte',
 'Ricky Bones',
 'Jeremy Hernandez',
 'Matt Maysey',
 'Dan Murphy',
 'Omar Olivares',
 'Darrin Reichle',
 'Rafael Valdez',
 'Dennis Cook',
 'Pat Combs',
 'Todd Frohwirth',
 'Jason Grimsley',
 'Chuck McElroy',
 'Andy Ashby',
 'Amalio Carreno',
 'Chuck Malone',
 'Brad Moore',
 'Scott Service',
 'Doug Bair',
 'Bob Patterson',
 'Mike York',
 'Stan Belinda',
 'Scott Ruskin',
 'Mike Jeffcoat',
 'Gary Mielke',
 'John Barfield',
 'Brian Bohanon',
 'David Lynch',
 'Ramon Manon',
 'Robb Nen',
 'Mark Petkovsek',
 'Jack Armstrong',
 'Mike Roesler',
 'Keith Brown',
 'Butch Henry',
 'Keith Kaiser',
 'Tim Layana',
 'Rosario Rodriguez',
 'Eric Hetzel',
 'Mike Rochford',
 'Daryl Irvine',
 'Dana Kiecker',
 'Josias Manzanillo',
 'Steve Crawford',
 'Kevin Appier',
 'Jose DeJesus',
 'Carlos Maldonado',
 'Dennis Moeller',
 'Edwin Nunez',
 'Kevin Ritz',
 'Brian Dubois',
 'Mike Schwabe',
 'Scott Aldred',
 'Shawn Holman',
 'Randy Nosek',
 'Dave Richards',
 'Don Vesling',
 'Steve Wapnick',
 'Mike Dyer',
 'Tim Drummond',
 'Mark Guthrie',
 'Kevin Tapani',
 'Paul Abbott',
 'Willie Banks',
 'Larry Casian',
 'Pete Delkus',
 'Park Pittman',
 'David West',
 'Jimmy Williams',
 'Grady Hall',
 'Roberto Hernandez',
 'Greg Hibbard',
 'Jerry Kutzler',
 'Scott Radinsky',
 'Jose Segura',
 'Chuck Cary',
 'Clay Parker',
 'Dave Eiland',
 'Alan Mills',
 'Willie Smith',
 'Scott Lewis',
 'Al Osuna',
 'Darryl Kile',
 'Joe Klink',
 'Steve Chitren',
 'Joe Turek',
 'Denis Boucher',
 'Ricky Rhodes',
 'Mike Timlin',
 'Steve Avery',
 'Paul Marak',
 'Chris Boslo',
 'Mark Lee',
 'Shawn Boskie',
 'Heathcliff Slocumb',
 'Jim Neidinger',
 'Mike James',
 'Steve Olin',
 'Charles Nagy',
 'Bruce Egloff',
 'Russ Swan',
 'Rich Delucia',
 'Pete Schourek',
 'Doug Simons',
 'Chris Nabholz',
 'Brian Barnes',
 'Greg McCarthy',
 'Jose Mesa',
 'Rich Rodriguez',
 'Frank Seminara',
 'Vicente Palacios',
 'Randy Tomlin',
 'Kip Gross',
 'Chris Hammond',
 'Gino Minutelli',
 'Dana Klecker',
 'Jeff Gray',
 'Dan Gakeler',
 'Mark Leiter',
 'Scott Erickson',
 'Wayne Edwards',
 'Alex Fernandez',
 'Brian Drahman',
 'Chris Beasley',
 'Joe Grahe',
 'Joe Slusarski',
 'Kirk Dressendorfer',
 'Bruce Walton',
 'Johnny Guzman',
 'Vincent Horsman',
 'Juan Guzman',
 'David Weathers',
 'Doug Henry',
 'Jim Austin',
 'Rheal Cormier',
 'Bob Scanlan',
 'Rudy Seanez',
 'Rod Beck',
 'Gil Heredia',
 'Mike Thomas',
 'Calvin Jones',
 'Dave Fleming',
 'Anthony Young',
 'Jeff Fassero',
 'Chris Haney',
 'Jonathan Hurst',
 'Matt Karchner',
 'Jim Poole',
 'Mike Mussina',
 'Jim Lewis',
 'Jose Melendez',
 'Wally Ritchie',
 'Kyle Abbott',
 'Cliff Brantley',
 'Denny Neagle',
 'Miguel Batista',
 'Paul Miller',
 'Bob Sebra',
 'Terry Mathews',
 'Steve Fireovid',
 'Hector Fajardo',
 'Milt Hill',
 'Steve Foster',
 'Mike Gardiner',
 'Peter Hoy',
 'Mike Magnante',
 'Joel Johnston',
 'Mike Munoz',
 'John Doherty',
 'John Kiely',
 'Carl Willis',
 'Tom Edens',
 'Pat Mahomes',
 'Wilson Alvarez',
 'Steve Howe',
 'Scott Kamieniecki',
 'Jeff Johnson',
 'Jerry Nielsen',
 'Mark Holzemer',
 'Brian Williams',
 'Mike Mohler',
 'Greg McMichael',
 'Cal Eldred',
 'Mark Kiefer',
 'Graeme Lloyd',
 'Donovan Osborne',
 'Rene Arocha',
 'Pedro Astacio',
 'Bryan Hickerson',
 'Kevin Rogers',
 'Greg Brummett',
 'Rick Huisman',
 'Mark Clark',
 'Mike Christopher',
 'Jeff Mutis',
 'Alan Embree',
 'Tom Kramer',
 'Dave Mlicki',
 'Kerry Woodson',
 'Dave Wainhouse',
 'John Cummings',
 'Mike Hampton',
 'Trevor Hoffman',
 'Richie Lewis',
 'Kip Yaughn',
 'Mike Draper',
 'Kent Bottenfield',
 'Arthur Rhodes',
 'Tim Scott',
 'Kerry Taylor',
 'Bob Ayrault',
 'Tyler Green',
 'Tim Wakefield',
 'Steve Cooke',
 'Blas Minor',
 'Paul Wagner',
 'Matt Whiteside',
 'Barry Manuel',
 'Dan Smith',
 'Tim Pugh',
 'Willie Canate',
 'Paul Quantrill',
 'Ken Ryan',
 'Darren Holmes',
 'David Nied',
 'Steve Reed',
 'Rusty Meacham',
 'Hipolito Pichardo',
 'Billy Brewer',
 'Dave Haas',
 'Greg Gohr',
 'Mike Trombley',
 'Rodney Bolton',
 'Sam Militello',
 'Bob Wickman',
 'Mike Humphreys',
 'Mike Butcher',
 'Phil Leftwich',
 'Todd Jones',
 'Shane Reynolds',
 'Todd Van Poppel',
 'Billy Taylor',
 'Steve Karsay',
 'John Briscoe',
 'Carlos Reyes',
 'Woody Williams',
 'Scott Brow',
 'Paul Menhart',
 'Paul Spoljaric',
 'Mark Wohlers',
 'Jeff Bronkey',
 'Jose Mercedes',
 'Tom Urbani',
 'Allen Watson',
 'Jim Bullinger',
 'Steve Trachsel',
 'Jessie Hollins',
 'Darren Dreifort',
 'Chan Ho Park',
 'Salomon Torres',
 'Matt Turner',
 'Jerry Dipoto',
 'Jeff Nelson',
 'Bobby Ayala',
 'Tim Davis',
 'Kevin King',
 'Pat Rapp',
 'Eric Hillman',
 'David Telgheder',
 'Bobby J. Jones',
 'Pedro J. Martinez',
 'Kirk Rueter',
 'Brad Pennington',
 'Doug Brocail',
 'Tim Mauser',
 'Pedro A. Martinez',
 'Tim Worrell',
 'Scott Sanders',
 'A.J. Sager',
 'Mike Williams',
 'Bobby Munoz',
 'Jeff Juden',
 'Mark Dewey',
 'Ravelo Manzanillo',
 'Rick White',
 'Roger Pavlik',
 'Steve Dreyer',
 'James Hurst',
 'Darren Oliver',
 'Johnny Ruffin',
 'Hector Carrasco',
 'Kevin Jarvis',
 'Aaron Sele',
 'Armando Reynoso',
 'Marcus Moore',
 'Scott Frederickson',
 'Keith Garagozzo',
 'Carlos Pulido',
 'Jason Bere',
 'Jeff Schwarz',
 'Sterling Hitchcock',
 'Brian James Anderson',
 'Russ Springer',
 'Troy Percival',
 'John Hudek',
 'Dave Veres',
 'Ross Powell',
 'Jim Dougherty',
 'Mark Acre',
 'Ariel Prieto',
 'Darren Hall',
 'Tim Crabtree',
 'Ricky Jordan',
 'Pedro Borbon',
 'Brad Clontz',
 'Mike Ignasiak',
 'Brian Givens',
 'Scott Karl',
 'Al Reyes',
 'Ron Rightnowar',
 'Sid Roberson',
 'Steve Sparks',
 'Kevin Foster',
 'Turk Wendell',
 'Rich Garces',
 'Ismael Valdez',
 'Joey Eischen',
 'Rick Gorecki',
 'Greg Hansell',
 'Hideo Nomo',
 'Jose Parra',
 'William Vanlandingham',
 'Enrique Burgos',
 'Shawn Barton',
 'Ken Greer',
 'Chris Hook',
 'Steve Mintz',
 'Joe Rosselli',
 'Julian Tavarez',
 'Chad Ogea',
 'Bill Risley',
 'Rafael Carmona',
 'Bob Wells',
 'Bob Murphy',
 'John Johnstone',
 'Matt Mantei',
 'Tim Bogar',
 'Bill Pulsipher',
 'Pete Walker',
 'Carlos Perez',
 'B.J. Wallace',
 'Gabe White',
 'Armando Benitez',
 'Mike Oquist',
 'John DeSilva',
 'Scott Klingenbeck',
 'Joey Hamilton',
 'Donnie Elliott',
 'Bryce Florie',
 'Andres Berumen',
 'Glenn Dishman',
 'Toby Borland',
 'Ricky Bottalico',
 'Michael Mimbs',
 'Dan Miceli',
 'Jason Christiansen',
 'John Ericks',
 'John Hope',
 'Esteban Loaiza',
 'Jeff McCurry',
 'Steve Parris',
 'Ed Vosberg',
 'Jose Alberro',
 'Terry Burrows',
 'Chris Nichting',
 'Jeff Branson',
 'C.J. Nitkowski',
 'Vaughn Eshelman',
 'Joe Hudson',
 'Frank Rodriguez',
 'Curtis Leskanic',
 'Juan Acevedo',
 'Roger Bailey',
 'Dilson Torres',
 'Sean Bergman',
 'Felipe Lira',
 'David Maxcy',
 'Dave Stevens',
 'Eddie Guardado',
 'Rich Robertson',
 'Erik Schullstrom',
 'Brad Radke',
 'Tim Fortugno',
 'Brian Keyser',
 'Joe Ausanio',
 'Brian Boehringer',
 'Andy Pettitte',
 'Mariano Rivera',
 'Ken Edenfield',
 'Jeff Tabaka',
 'Alvin Morman',
 'Mark Small',
 'Buddy Groom',
 'Aaron Small',
 'Don Wengert',
 'Doug Johns',
 'Steve Montgomery',
 'Giovanni Carrara',
 'Jeff Ware',
 'Jason Schmidt',
 'Terrell Wade',
 'Jamie McAndrew',
 'Mike Potts',
 'T.J. Mathews',
 'Cory Bailey',
 'Alan Benes',
 'Mike Busby',
 'Terry Adams',
 'Rodney Myers',
 'Osvaldo Fernandez',
 'Steve Bourgeois',
 'Paul Creek',
 'Daron Kirkreit',
 'Edwin Hurtado',
 'Bob Wolcott',
 'Wilson Heredia',
 'Jason Isringhausen',
 'Paul Byrd',
 'Robert Person',
 'Paul Wilson',
 'Omar Daal',
 'Jimmy Haynes',
 'Doug Bochtler',
 'Mike J. Grace',
 'Rich Hunter',
 'Jon Lieber',
 'Lee Hancock',
 'Francisco Cordova',
 'Chris Howard',
 'Mark Brandenburg',
 'Roger Salkeld',
 'Jeff Suppan',
 'Lance Painter',
 'Mark Thompson',
 'Bryan Rekar',
 'Jason Jacome',
 'Jim Converse',
 'Jim Pittsley',
 'Mike Myers',
 'Greg Keagle',
 'Clint Sodowsky',
 'LaTroy Hawkins',
 'Erik Bennett',
 'Dan Naulty',
 'Bill Simas',
 'Larry Thomas',
 'Mark Hutton',
 'Shigetoshi Hasegawa',
 'Dennis Springer',
 'Mike Holtz',
 'Jason Dickson',
 'Pep Harris',
 'Billy Wagner',
 'Jose Lima',
 'Ramon Garcia',
 'Tom Martin',
 'Chris Holt',
 'Dave Tilgheder',
 'Willie Adams',
 'Luis Andujar',
 'Joe Borowski',
 'Ron Villone',
 "Jeff D'Amico",
 'Rich Batchelor',
 'Brian Barber',
 'John Frascatore',
 'Eric Ludwick',
 'Dave Swartzbaugh',
 'Ramon Tatis',
 'Shawn Estes',
 'Dan Carlson',
 'Joe Roa',
 'Chad Curtis',
 'Paul Shuey',
 'Albie Lopez',
 'Bartolo Colon',
 'Steve Kline',
 'Jay Powell',
 'Rick Helling',
 'Kurt Miller',
 'Felix Heredia',
 'Tony Saunders',
 'Matt Whisenant',
 'Rick Reed',
 'Ricardo Jordan',
 'Derek Wallace',
 'Ugueth Urbina',
 'Dustin Hermanson',
 'Matt Wagner',
 'Marc Valdes',
 'Rocky Coppinger',
 'Mike Johnson',
 'Dario Veras',
 'Will Cunnane',
 'Scott Ruffcorn',
 'Ron Blazier',
 'Calvin Maduro',
 'Erik Plantenberg',
 'Edgar Ramos',
 'Jerry Spradlin',
 'Jeff Granger',
 'Marc Wilkins',
 'Matt Ruebel',
 'Rich Loiselle',
 'Ricardo Rincon',
 'Danny Patterson',
 'Julio F. Santana',
 'Robinson Checo',
 'John Wasdin',
 'Jamey Wright',
 'Garvin Alston',
 'John Burke',
 'Jose Rosado',
 'Jamie Bluma',
 'Brian Bevil',
 'Glendon Rusch',
 'Jamie Walker',
 'Justin Thompson',
 'Ramon Fermin',
 'Fernando Hernandez',
 'Brian Moehler',
 'Francisco Rodriguez',
 'Todd Ritchie',
 'James Baldwin',
 'Jeff Darwin',
 'Michael Bertotti',
 'Alan Levine',
 'Carlos Castillo',
 'Jose Cabrera',
 'Trever Miller',
 'John Halama',
 'Brad Rigby',
 ...]

In [32]:
# How to find out all missing values count in all columns ?

In [33]:
m.isnull().sum()

Year        0
Player      0
Salary      0
Position    0
Team        0
dtype: int64

In [34]:
# Show Team wise Salaries Total ?

In [38]:
h = m.groupby(pd.Grouper(key='Team')).sum()
h=['Salary']

In [39]:
h=a.groupby(pd.Grouper(key='Team')).sum()   # not sure about this one
h['Salary']

AttributeError: 'list' object has no attribute 'groupby'

In [40]:
# Count ALL Player Team wise ?

In [ ]:
i = m